# Generated by Django 4.2 on 2023-05-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Client',
            new_name='client',
        ),
    ]
